arch: dccrn
seed: 0
train_path: none
val_path: none
dataset:
  segment_length: 0.0
  overlap_length: 0.0
  fs: 16000
  sources:
  - mixture
  - foreground
  segment_strategy: pass
  max_segment_length: 0.0
  tar: true
trainer:
  workers: 4
  epochs: 100
  device: cuda
  batch_sampler: bucket
  batch_size: 128
  num_buckets: 10
  dynamic_batch_size: true
  fs: 16000
  ema: false
  ema_decay: 0.999
  ignore_checkpoint: false
  preload: false
  ddp: false
  rank: 0
  use_wandb: false
  profile: false
  val_metrics: !!set
    estoi: null
    snr: null
    pesq: null
  val_period: 10
  use_amp: true
  compile: false
  save_on_epochs: []
model:
  stft_frame_length: 512
  stft_hop_length: 128
  stft_window: hann
  channels:
  - 16
  - 32
  - 64
  - 128
  - 128
  - 128
  kernel_size: !!python/tuple
  - 5
  - 2
  stride: !!python/tuple
  - 2
  - 1
  padding: !!python/tuple
  - 2
  - 0
  output_padding: !!python/tuple
  - 1
  - 0
  lstm_channels: 128
  lstm_layers: 2
  use_complex_batchnorm: false
  criterion: snr
  optimizer: Adam
  learning_rate: 0.0001
