arch: idmse
seed: 0
train_path: none
val_path: none
dataset:
  segment_length: 0.0
  overlap_length: 0.0
  fs: 16000
  sources:
  - mixture
  - foreground
  segment_strategy: pass
  max_segment_length: 0.0
  tar: true
trainer:
  workers: 4
  epochs: 100
  device: cuda
  batch_sampler: bucket
  batch_size: 64
  num_buckets: 10
  dynamic_batch_size: true
  fs: 16000
  ema: true
  ema_decay: 0.999
  ignore_checkpoint: false
  preload: false
  ddp: false
  rank: 0
  use_wandb: false
  profile: false
  val_metrics: !!set
    pesq: null
    estoi: null
    snr: null
  val_period: 10
  use_amp: true
  compile: false
  save_on_epochs: []
model:
  stft_frame_length: 512
  stft_hop_length: 128
  stft_window: hann
  stft_compression_factor: 0.5
  stft_scale_factor: 0.15
  stft_discard_nyquist: true
  sde_name: brever-oucosine
  sde_stiffness: 0.0
  sde_ve_sigma_min: 0.05
  sde_ve_sigma_max: 0.5
  sde_vp_beta_min: 0.01
  sde_vp_beta_max: 1.0
  sde_cosine_lambda_min: -12.0
  sde_cosine_lambda_max: .inf
  sde_cosine_shift: 3.0
  sde_cosine_beta_clamp: 10.0
  sde_bb_scaling: 0.1
  solver_name: edm
  solver_num_steps: 16
  solver_edm_schurn: .inf
  solver_edm_smin: 0.0
  solver_edm_smax: .inf
  solver_edm_snoise: 1.0
  solver_pc_corrector_steps: 1
  solver_pc_corrector_snr: 0.5
  net_base_channels: 128
  net_channel_mult:
  - 1
  - 2
  - 2
  - 2
  net_num_res_blocks: 1
  net_noise_channels: 256
  net_emb_channels: 512
  net_fir_kernel:
  - 1
  - 3
  - 3
  - 1
  net_attn_resolutions:
  - 0
  net_attn_bottleneck: true
  preconditioning_cskip: edm
  preconditioning_cout: edm
  preconditioning_cin: edm
  preconditioning_cnoise: edm
  preconditioning_cshift: edm
  preconditioning_weight: edm
  preconditioning_sigma_data: 0.1
  t_eps: 0.01
  criterion: mse
  optimizer: Adam
  learning_rate: 0.0001
