arch: tfgridnet
seed: 0
train_path: none
val_path: none
dataset:
  segment_length: 0.0
  overlap_length: 0.0
  fs: 16000
  sources:
  - mixture
  - foreground
  segment_strategy: pass
  max_segment_length: 0.0
  tar: true
  dynamic_mixing: false
  dynamic_mixtures_per_epoch: 1000
trainer:
  workers: 4
  epochs: 100
  device: cuda
  batch_sampler: bucket
  batch_size: 64
  num_buckets: 10
  dynamic_batch_size: true
  fs: 16000
  ema: false
  ema_decay: 0.999
  ignore_checkpoint: false
  preload: false
  ddp: false
  rank: 0
  use_wandb: false
  profile: false
  val_metrics: !!set
    pesq: null
    estoi: null
    snr: null
  val_period: 10
  use_amp: true
  compile: false
  save_on_epochs: []
model:
  n_srcs: 1
  n_fft: 256
  stride: 128
  window: hann
  n_layers: 6
  lstm_hidden_units: 128
  attn_n_head: 4
  attn_approx_qk_dim: 512
  emb_dim: 32
  emb_ks: 4
  emb_hs: 4
  activation: PReLU
  eps: 1.0e-05
  criterion: multiresyu
  optimizer: Adam
  learning_rate: 0.001
  grad_clip: 1.0
