MODELS: models/
DATASETS: data/datasets/
DCASE: data/external/DCASE-16kHz-mono-flac/
SURREY: data/external/SURREY/
TIMIT: data/external/TIMIT/
HUDDERSFIELD: data/external/Huddersfield/
LIBRI: data/external/LibriSpeech/
IEEE: data/external/IEEE/
ASH: data/external/ASH/
ICRA: data/external/ICRA/
HINT: data/external/HINT/
ARCTIC: data/external/ARCTIC/
ARTE: data/external/ARTE/
DEMAND: data/external/DEMAND/
NOISEX: data/external/NOISEX/
AIR: data/external/AACHEN/
CATT: data/external/CATT/
AVIL: data/external/AVIL/
ELOSPHERES: data/external/ELOSPHERES/
BRAS: data/external/BRAS/
VCTK: data/external/VCTK-16kHz/
WSJ0: data/external/WSJ0-convert/
CLARITY: data/external/Clarity-16kHz-flac/
